### ISSUE TITLE
你好，我想在电脑端用微信扫码登录，根据你的说明感觉是wechat_open，但提示无法驱动？

### ISSUE THREAD

**Issue by kl521516** [overtrue/socialite#102]
你好，我想在电脑端用微信扫码登录，根据你的说明感觉是wechat_open，但提示无法驱动？

错误信息如下：
Driver [wechat_open] not supported.

我同时使用了微信授权登录和QQ授权登录，都可以正常使用。

——————————————————————————————————————
然后我又看你写了如下说明，我就试着用scopes(['snsapi_login'])方式，但是报redirect_uri 参数错误

WeChat scopes:
snsapi_base, snsapi_userinfo - Used to Media Platform Authentication.
snsapi_login - Used to web Authentication.

$response = $socialite->driver('wechat')->scopes(['snsapi_login'])->redirect();

**Comment by overtrue** [comment]
正确的用法是使用 

```php
$socialite->driver('wechat')->scopes(['snsapi_login'])->redirect()
```
报 redirect_uri 参数错误的话需要确认你当前的 URL 是否与你配置的 URL 一致，如果不是跳回到当前 URL 的话，你需要指定 callback 地址：

```php
$redirect = 'https://xxxx.xxx.com/path/to/callback';

$socialite->driver('wechat')->scopes(['snsapi_login'])->redirect($redirect); 
```

**Comment by kl521516** [comment]
我设置了callback地址也报redirect_uri 参数错误，详细代码如下，QQ和微信授权登录都这样弄的，那些都可以正常运行

$config = [
	'wechat' => [
		'client_id'  =>  "123123",
		'client_secret'  =>  "123123",
		'redirect'  =>  "http://abc.cn/wechat_open_callback",
	],
];

$socialite = new SocialiteManager($config);
$response = $socialite->driver('wechat')->scopes(['snsapi_login'])->redirect();
$response->send();

**Comment by overtrue** [comment]
那就是你在微信开放平台配置的 url 与这里的 redirect 不一样。

**Comment by kl521516** [comment]
https://open.weixin.qq.com/
微信公众号授权登录需要配置这个url，但微信开放平台没有这一项配置

**Comment by mingyoung** [comment]
@kl521516 配置「回调域名」

**Comment by kl521516** [comment]
@mingyoung  请问在哪配置回调域名？

**Comment by mingyoung** [comment]
开放平台后台 - 网站应用

自己找下就找到了

**Comment by kl521516** [comment]
谢谢，我明白了，我一直以为是开放平台后台-公众号这一项。
