### ISSUE TITLE
如何实现微信电脑登录与微信手机登录同时存在?

### ISSUE THREAD

**Issue by falstack** [overtrue/socialite#109]
我的应用同时要支持 PC 微信登录和 H5 微信登录

那么我就有两个微信的 client_id 和 client_secret，但是我调用 driver 的时候都是要调用 wechat，通过改变 scope 来判断是 PC 还是 H5，但是 APP_ID 和 APP_SECRET 无法更改，那么就只有一个能调通，另一个没有权限

是我哪里理解错了吗？

**Comment by overtrue** [comment]
你可以手动实例化，创建一个 PC 一个 H5 ，根据 UserAgent 等来判断然后决定使用哪个实例即可。

**Comment by falstack** [comment]
thanks
