### ISSUE TITLE
LinkedIn error

### ISSUE THREAD

**Issue by vkamelin** [overtrue/socialite#110]
This resource is no longer available under v1 APIs

**Comment by overtrue** [comment]
OK, I will check this after I finish my works.

**Comment by abhij89** [comment]
has this been updated? support for linkedin v2.0?

**Comment by overtrue** [comment]
@vkamelin @abhij89 Can anyone help me test the latest code version of linkedin login?

**Comment by hotrush** [comment]
@overtrue i think that `r_basicprofile` scope is deprecated, need to use `r_liteprofile`

https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq
