### ISSUE TITLE
Call to undefined method Illuminate\Session\Store::set()

### ISSUE THREAD

**Issue by hedeqiang** [overtrue/socialite#116]
超哥，最近忽然出现这个问题
```
Call to undefined method Illuminate\Session\Store::set()
```

![image](https://user-images.githubusercontent.com/31909061/53501747-b29cfd00-3ae7-11e9-8455-6da973cb8fa4.png)

Laravel Framework 5.7.28

overtrue/socialite (2.0.3 => 2.0.6)

**Comment by qbhy** [comment]
2.0.3没问题的，后面的版本makeState方法又出了这种问题，不知道是不是有其他考虑 ？ @overtrue

**Comment by huangdijia** [comment]
@overtrue
线上项目挂了，可以先修复吗？

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/releases/tag/2.0.7
