### ISSUE TITLE
目前能否自定义 Provider ? 要是可以就更完善了

### ISSUE THREAD

**Issue by achais** [overtrue/socialite#126]
看了一下有人希望支持 支付宝, 钉钉 等等, 大佬一辈子都写不完这些需求的.
要是像 easy-sms 一样支持自定义 Gateway 就轻松多了.
(毕竟我用了自定义Gateway 在此感谢超哥)

**Comment by overtrue** [comment]
支持自定义 provider 的哈，SocialiteManager 的 extend 方法。

**Comment by achais** [comment]
> 支持自定义 provider 的哈，SocialiteManager 的 extend 方法。

恩 感谢大佬, readme 上没看到看了下源码找到了 extend , 所以 close 了.
