### ISSUE TITLE
安哥，您好！怎么获取QQ互联的unionid？

### ISSUE THREAD

**Issue by bmkj** [overtrue/socialite#132]
这样获取的unionid是空的：
$responseRs = $socialite->driver(‘qq’)->user();
print_r($responseRs);

**Comment by bmkj** [comment]
还是这样子？
$responseRs = $socialite->driver('qq')->withUnionId()->user();

**Comment by overtrue** [comment]
如果官方返回了就在 `$socialite->driver('qq')->user()->getOriginal()`  中，否则就没办法。

**Comment by bmkj** [comment]
谢谢
