### ISSUE TITLE
"code" missing for linkedin? what is this "code" please?

### ISSUE THREAD

**Issue by rajan77** [overtrue/socialite#139]
Hello

$config = [
    'linkedin' => [
        'client_id' => $linkedin_client_id,
        'client_secret' => $linkedin_client_secret,
        'redirect' => $myURL,
    ],
];

$socialite = new SocialiteManager($config);

$user = $socialite->driver('linkedin')->user();

I get an error back saying 
Fatal error:  Uncaught Overtrue\Socialite\AuthorizeFailedException: Authorize Failed: {"error":"invalid_request","error_description":"A required parameter \"code\" is missing"} in …. vendor/overtrue/socialite/src/Providers/AbstractProvider.php:448

Please help!

**Comment by overtrue** [comment]
Plz read: https://github.com/overtrue/socialite#usage

**Comment by staqd** [comment]
![image](https://user-images.githubusercontent.com/73796129/100353449-ca702080-2fee-11eb-806f-70e0e9109c71.png)

make sure your app has been approved for the "Sign In With LinkedIn" process.

**Comment by rassemdev** [comment]
> https://github.com/overtrue/socialite#usage

That's solved my problem, thanks
