### ISSUE TITLE
AbstractProvider.php 第412行是不是有问题？

### ISSUE THREAD

**Issue by lyphp** [overtrue/socialite#141]
vendor\overtrue\socialite\src\Providers\AbstractProvider.php 第412行的getSession方法，在easywechat使用企业号获取userid时，结果为null，没有get()方法。不知道有其他小伙伴遇到过没？

$state = $this->request->getSession()->get('state');

**Comment by lyphp** [comment]
新人入学，希望老师指点， 查看源代码getSession()方法是获取到$this->session，为一个属性值，怎么还可以调用get方法呢？

**Comment by chanble** [comment]
这个和你的项目是否启用session有关
