### ISSUE TITLE
how to add a  custom param to the url， then the callback url can get it

### ISSUE THREAD

**Issue by LaJun** [overtrue/socialite#148]

**Comment by overtrue** [comment]
```php
$response = $socialite->driver('google')
                    ->with(['hd' => 'example.com'])->redirect();
```

**Comment by LaJun** [comment]
> ```
> $response = $socialite->driver('google')
>                     ->with(['hd' => 'example.com'])->redirect();
> ```
获取跳转url
$param = $request->query();
        $param['type'] = $type;
        $response = $socialite->driver($type)->with(['type', $type])->redirect()->getTargetUrl();
        return $this->success($response);
回调url显示中没有type参数传递过来

**Comment by overtrue** [comment]
@LaJun 要对方网站支持才行啊，否则你就只有两个选择：
1. 存到 session
2. 在 callback url 上加变量

**Comment by LaJun** [comment]
@overtrue 知道了多谢

**Comment by overtrue** [comment]
不客气
