### ISSUE TITLE
应该开放下getAuthUrl 这个方法

### ISSUE THREAD

**Issue by pslxx** [overtrue/socialite#157]
前后端分离的项目,我想前端请求接口获取到这个URL地址,
前端控制打开逻辑,比如跳转,或者小窗口打开

**Comment by pslxx** [comment]
同时希望能开放 getUserByToken 这个方法
尤其是在移动端获取code之后,获取token,然后手动调用该方法获取用户信息.做接下来的逻辑处理

**Comment by overtrue** [comment]
1. 获取跳转链接的 URL，`redirect()` 返回的就是一个 RedirectResponse 对象，取它的 URL 直接调用方法即可:
https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L168-L180
```php
$response = $socialite->driver('github')->redirect();

$url = $response->getTargetUrl();
```

2. 根据 code 拿 user：

https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L186

```php
$accessToken = new \Overtrue\Socialite\ AccessToken(['access_token' => 'your-token-here']);
$user = $socialite->driver('github')->user($accessToken);
```

**Comment by pslxx** [comment]
谢谢
