### ISSUE TITLE
使用access_token返回missing openid的错误

### ISSUE THREAD

**Issue by tradzero** [overtrue/socialite#16]
请问是不是要另外指定openid？ 应用场景是app获取到token后 传递到服务器，服务器通过这个token获取用户的其他信息进行校验
代码部分：
        
```
        $socialite = new SocialiteManager($this->config);
        $accessToken = new AccessToken(['access_token' => $token]);
        $user = $socialite->driver('wechat')->user($accessToken);

```
token是APP端立即获取到的 应该不存在过期问题

**Comment by overtrue** [comment]
@tradzero 你的 token 怎么获取的？流程是怎么样的？

**Comment by tradzero** [comment]
@overtrue 使用的第三方（友盟）提供的封装的第三方登录获取的token 流程是直接调取的友盟SDK里的第三方登录 APPKEY是自己申请的 服务器跟APP端都是一样的

**Comment by overtrue** [comment]
那也许那个 token 与这个不是一个东西吧， 这个 token 是从网页跳转过去用户点击授权后得到的 token, 所以你得先确认它们是一个东西，并且使用其它组件授权的是否能与网页授权的通用，如果不通用也是没办法的事情。

**Comment by tradzero** [comment]
@overtrue 好的 谢谢大大

**Comment by tradzero** [comment]
@overtrue 刚才测试通过了 在`$accessToken = new AccessToken(['access_token' => $token]);` 这里 还要多传入openid字段`$accessToken = new AccessToken(['access_token' => '$token', 'openid' => 'openid']);`
这样就可以了 是我没仔细看官方文档 我的原因

**Comment by overtrue** [comment]
@tradzero 哦。那就好
