### ISSUE TITLE
【question】我想安装dev分支来测试，但是提示php版本不符合，我看你的readme.md说的是php>=7.3即可，我的是7.3.18

### ISSUE THREAD

**Issue by ShuiPingYang** [overtrue/socialite#177]
```php

  [InvalidArgumentException]
  Package overtrue/socialite at version dev-develop has a PHP requirement incompatible with your PHP
   version (7.3.18)
```

**Comment by overtrue** [comment]
7.4+ 哈 https://github.com/overtrue/socialite/blob/develop/composer.json#L20

**Comment by uptutu** [comment]
README 里写的是 `
 "require": {
    "php": ">=7.4",
}` 呀亲~
请看 [dev 分支](https://github.com/overtrue/socialite/tree/develop)

**Comment by ShuiPingYang** [comment]
这个一下子跳跃太大了，大部分php还是7.3以下吧

**Comment by overtrue** [comment]
@ShuiPingYang 如果大家都去兼容旧版，就会有越来越多的人不去升级，这个过程就会死循环下去，然而，从 PHP 7.0（2015发布的）升级到 PHP 7.4 其实也就两小时不到的工作量。

PS: 我们已经在内部尝试 PHP 8 了，等正式发布就会切换过去。
