### ISSUE TITLE
企业微信扫码登录回调报 cURL error 3

### ISSUE THREAD

**Issue by tlerbao** [overtrue/socialite#181]
扫码登录成功到回调报 curl error 3

![image](https://user-images.githubusercontent.com/20442232/87909508-f3116800-ca9a-11ea-84de-8bbadb19206e.png)

下面是callbak方法
```
        $config = [
            'wework' => [
                'client_id' => 'ww5763fa6xxxx',
                'client_secret' => 'qB1J-g1fKU0CpJFe2nJulZbFpS2xxxxxxxxx',
                'redirect' => 'http://tp6.test/index/callback',
            ],
        ];

        $socialite = new SocialiteManager($config);

        $user = $socialite->driver('wework')->user();
        dd($user);
```

**Comment by overtrue** [comment]
https://cloud.tencent.com/developer/article/1453135

**Comment by tlerbao** [comment]
@overtrue 我并没有充分理解您的意思，首先我升级overtrue/wechat到最4.2.30版本，问题依旧；然后至于后面说的换行的问题，我目前本机（Win10）就这个错误，push代码到服务器(centos)也是一样。

请问我还是哪里没搞对吗？

我的环境：Win10+PHP7.3+VSCode

**Comment by overtrue** [comment]
检查你的配置是否有特殊符号（可能是手误导致，也可能是不可见的特殊符号），或者抓包看一下回调过程产生的网络请求 URL 是否包含特殊符号或其他异常内容，因为这个错误是 cURL报出来的，就是出现了非法字符。

**Comment by tlerbao** [comment]
@overtrue 难为我等菜鸡了，不会抓包啊；我现在是生成并正确跳转到了腾讯企业微信的扫码页面，扫码成功登陆后，返回我的回调地址，报这个错误，完全不知道怎么一回事。

**Comment by overtrue** [comment]
原因是：使用了自己 Host 的域名，无法正常通信。
