### ISSUE TITLE
开发者您好，我在使用"overtrue/socialite": "3.0.2" 版本时，Github有出现Fatal error [-1]: Authorize Failed: []

### ISSUE THREAD

**Issue by DOUBIGROUP** [overtrue/socialite#188]
您好，我在使用"overtrue/socialite": "3.0.2" 版本时，使用Github方式登录有出现以下错误
```
Fatal error [-1]: Authorize Failed: []
Triggered in /app/vendor/overtrue/socialite/src/Providers/Base.php at line 286
```
但是我使用QQ方式是正常的

**Comment by overtrue** [comment]
从报错来看就是授权失败哦，检查一下 appkey 和 id 是否正确，服务器是否能跟 github 正常通信等。

**Comment by kids-return** [comment]
https://github.com/overtrue/socialite/commit/b8eb4465c56b02be51ebfe63a9a3bd075ad058c4
这里的问题
导致 github 返回的是 query 字符串，而不是 json 字符串
需要 accept: application/json 
这里改回来 微博单独处理吧 
@overtrue

**Comment by kids-return** [comment]
因为一定需要 json 才能正确处理，这样也许可以 https://github.com/overtrue/socialite/pull/190
