### ISSUE TITLE
微博静默授权是否可以支持?

### ISSUE THREAD

**Issue by wilbur-oo** [overtrue/socialite#189]
微博静默授权的base url有改变. 
[参考链接](https://open.weibo.com/wiki/%E7%BD%91%E9%A1%B5%E6%8E%88%E6%9D%83%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E5%9F%BA%E6%9C%AC%E4%BF%A1%E6%81%AF)

或者是否可以考虑设置修改baseUrl参数的setAuthUrl方法.

**Comment by overtrue** [comment]
授权地址没区别啊，都是 https://api.weibo.com/oauth2/authorize  https://github.com/overtrue/socialite/blob/master/src/Providers/Weibo.php#L19

**Comment by overtrue** [comment]
静默授权换 scope 就好了：

```php
$response = $socialite->create('weibo')->scopes(['snsapi_base'])->redirect();
```

**Comment by wilbur-oo** [comment]
> 授权地址没区别啊，都是 [api.weibo.com/oauth2/authorize](https://api.weibo.com/oauth2/authorize) [https://github.com/overtrue/socialite/blob/master/src/Providers/Weibo.php#L19](https://github.com/overtrue/socialite/blob/master/src/Providers/Weibo.php?rgh-link-date=2020-09-08T06%3A13%3A56Z#L19)
> 
> > **[第三方授权错误](https://api.weibo.com/oauth2/authorize)**
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/1472352?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[overtrue/socialite](https://github.com/overtrue/socialite)**:octocat: Socialite is an OAuth2 Authentication tool. It is inspired by laravel/socialite, you can easily use it without Laravel. - overtrue/socialite

这里有个pc和移动端的区别, 
![image](https://user-images.githubusercontent.com/7148309/92588355-71380100-f2cb-11ea-8d51-13d3ae036a5e.png)
如果没有更换基础域名的话, 直接修改scope的情况下, 会报没有appkey的错误, errcode为10006

**Comment by wilbur-oo** [comment]
有版本依赖冲突, 使用了直接引入socialite无法引入版本3, laravel-wechat 5.0.7 依赖的wechat为4.2.35, wechat依赖的socialite版本为2.0.16

**Comment by overtrue** [comment]
@wilbur-oo  已经发新版
