### ISSUE TITLE
Configuration went wrong even when followed exact instruction in README

### ISSUE THREAD

**Issue by sudipghimire533** [overtrue/socialite#191]
I just decided to start socialite in my current project and did as mentioned in README

**authorize.php**

```php
<?php
require_once 'vendor/autoload.php';

use Overtrue\Socialite\SocialiteManager;

$config = [
    'google' => [
        'client_id'     => '732681897443-************.apps.googleusercontent.com',
        'client_secret' => '0************************x',
        'redirect'      => 'http://localhost/callback.php',
    ],
];

$socialite = new SocialiteManager($config);

$url = $socialite->create('github')->redirect();`
But this is my error message
```
> PHP Fatal error:  Uncaught Error: Call to undefined method Overtrue\Socialite\SocialiteManager::create() in /home/sudip/Projects/Web/authorize.php:16

**Comment by sudipghimire533** [comment]
And also the callback.php is also configured properly and lookes like
`
<?php

use Overtrue\Socialite\SocialiteManager;

$config = [
    'google' => [
        'client_id'     => '732681897443-*****************.apps.googleusercontent.com',
        'client_secret' => '&^7^%%%%%%',
        'redirect'      => 'http://localhost/callback.php',
    ],
];

$socialite = new SocialiteManager($config);

$code = request()->query('code');

$user = $socialite->create('google')->userFromCode($code);
`

**Comment by overtrue** [comment]
Plz confirm the version of installed is 3.x：

```bash
$ composer info overtrue/sociailte
```

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/blob/master/src/SocialiteManager.php#L56

**Comment by sudipghimire533** [comment]
Ok that looks like I am having wrong version. But why is wrong version installed even tough i followed your instruction and my composer package is up-to-date

**Comment by overtrue** [comment]
@sudipghimire533 Haha, I don't know what happened, but if you managed to install 3.0, it's ok!
