### ISSUE TITLE
3.0版本企业微信网页授权在微信中发起支持

### ISSUE THREAD

**Issue by dobuledragon** [overtrue/socialite#192]
![image](https://user-images.githubusercontent.com/35892673/93070978-1d099400-f6b2-11ea-8264-40089b844e9e.png)
由于微信中获取到的是openid  所以一直报错

**Comment by overtrue** [comment]
企业微信的网页授权在微信里发起？

**Comment by dobuledragon** [comment]
是的

**Comment by overtrue** [comment]
那就继续用 2 版本吧，3 是大版本升级，不兼容哈。
