### ISSUE TITLE
2.0.16升级至2.0.18的建议

### ISSUE THREAD

**Issue by holajm** [overtrue/socialite#193]
2.0.16
overtrue/socialite/src/Providers/AbstractProvider.php :

```php
public function __construct(Request $request, $clientId, $clientSecret, $redirectUrl = null)
    {
        $this->request = $request;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->redirectUrl = $redirectUrl;
    }
```
====================================================================
2.0.18
overtrue/socialite/src/Providers/AbstractProvider.php :

```php
public function __construct(Request $request, $config)
    {
        $this->config = new Config($config);
        $this->request = $request;
        $this->redirectUrl = isset($config['redirect']) ? $config['redirect'] : null;
    }
```

在两个小版本的升级，底层的构造函数的参数改变，由于在overtrue/laravel-socialite 里会默认更新 overtrue/socialite的版本，有人基于这个基类进行进一步的封装，会导致更新时会带来不少麻烦，建议不要改变基类构造函数的参数

**Comment by overtrue** [comment]
问题呢？

**Comment by holajm** [comment]
> 问题呢？

刚刚更新问题描述啦，因为我基于AbstractProvider进行了进一步封装，在更新时就会遇到参数不匹配的问题

**Comment by overtrue** [comment]
确实没考虑到这部分用户的场景，我的疏漏，已经发布补丁版本，请更新后再试： https://github.com/overtrue/socialite/releases/tag/2.0.19

**Comment by holajm** [comment]
> 确实没考虑到这部分用户的场景，我的疏漏，已经发布补丁版本，请更新后再试： https://github.com/overtrue/socialite/releases/tag/2.0.19
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/1472352?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Release 2.0.19 · overtrue/socialite](/overtrue/socialite/releases/tag/2.0.19)**:octocat: Socialite is an OAuth2 Authentication tool. It is inspired by laravel/socialite, you can easily use it without Laravel. - overtrue/socialite

感谢大佬

**Comment by overtrue** [comment]
客气了
