### ISSUE TITLE
发布了2.0.18 以后 Refactor/user (#166) overtrue/laravel-wechat#295这个问题 又出来了

### ISSUE THREAD

**Issue by linshuboy** [overtrue/socialite#197]
发布了2.0.18 以后 Refactor/user (#166)  overtrue/laravel-wechat#295这个问题 又出来了 @overtrue

**Comment by overtrue** [comment]
到底哪个问题？麻烦描述清楚一下

**Comment by linshuboy** [comment]
https://github.com/overtrue/laravel-wechat/issues/295 这个问题,我昨天和他报同样的错误,查看源码发现是Refactor/user (#166) 这个pull 之后将原来已经解决的问题有带出来了.降级到2.0.16之后就没有报错了

**Comment by overtrue** [comment]
试试 https://github.com/overtrue/socialite/releases/tag/2.0.21

**Comment by linshuboy** [comment]
> 试试 https://github.com/overtrue/socialite/releases/tag/2.0.21

现在可以了,感谢!

**Comment by linshuboy** [comment]
现在报这个错误
![6d69664287e7e2c806f2e2fb8dcdcee2](https://user-images.githubusercontent.com/20389206/97077422-28879d80-1616-11eb-95ec-f1cbf4e505b1.jpg)

**Comment by linshuboy** [comment]
首次访问没有用户信息,存的时候报的这个错误

**Comment by gytai** [comment]
> 现在报这个错误
> ![6d69664287e7e2c806f2e2fb8dcdcee2](https://user-images.githubusercontent.com/20389206/97077422-28879d80-1616-11eb-95ec-f1cbf4e505b1.jpg)

我也报这个错。请问你解决了吗？

**Comment by overtrue** [comment]
@linshuboy 列出你的 overtrue/wechat 版本和 overtrue/socialite 版本

**Comment by ushell** [comment]
这个问题和刚提的issue #203 一样

版本环境:

`overtrue/wechat: 4.3.1` 自动引入了  "overtrue/socialite": "2.0.21"

问题原因：AccessTokenDelegate类的对象被当成 array使用了
