### ISSUE TITLE
Linkedin & Google Error

### ISSUE THREAD

**Issue by charliezstong** [overtrue/socialite#200]
Google: GuzzleHttp \ Exception \ InvalidArgumentException
Passing in the "body" request option as an array to send a request is not supported. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.

Please check: overtrue\socialite\src\Providers\Base.php ( tokenFromCode(string $code) )

Linkedin: Undefined index: firstName.preferredLocale.country

**Comment by overtrue** [comment]
Sorry, Try the dev-master branch again, please.

**Comment by charliezstong** [comment]
Thanks @overtrue

**Comment by overtrue** [comment]
@charliezstong ❤️
