### ISSUE TITLE
Base.php error

### ISSUE THREAD

**Issue by ginoking** [overtrue/socialite#201]
PHP Fatal error:  Uncaught Overtrue\Socialite\Exceptions\AuthorizeFailedException: Authorize Failed: {"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https:\/\/docs.github.com\/apps\/managing-oauth-apps\/troubleshooting-oauth-app-access-token-request-errors\/#bad-verification-code"} in /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php:296
Stack trace:
#0 /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php(105): Overtrue\Socialite\Providers\Base->normalizeAccessTokenResponse()
#1 /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php(67): Overtrue\Socialite\Providers\Base->tokenFromCode()
#2 /var/www/alpha/login1.php(18): Overtrue\Socialite\Providers\Base->userFromCode()
#3 {main}
  thrown in /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php on line 296

github、facebook、linkedin皆遇到

**Comment by tripbnb66** [comment]
I have the same issue for github, facebook, google and linked.

```
# composer info overtrue/socialite
name     : overtrue/socialite
descrip. : A collection of OAuth 2 packages.
keywords : Feishu, login, oauth, qcloud, qq, social, wechat, weibo
versions : * 3.0.6
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage :
source   : [git] https://github.com/overtrue/socialite.git 765941f858facdeff611d3f8652c8f8bfba3e0af
dist     : [zip] https://api.github.com/repos/overtrue/socialite/zipball/765941f858facdeff611d3f8652c8f8bfba3e0af 765941f858facdeff611d3f8652c8f8bfba3e0af
path     : /var/www/alpha/vendor/overtrue/socialite
names    : overtrue/socialite

autoload
psr-4
Overtrue\Socialite\ => src/

requires
ext-json *
ext-openssl *
guzzlehttp/guzzle ~6.0|~7.0
php >=7.4
symfony/http-foundation ^5.0
symfony/psr-http-message-bridge ^2.0

requires (dev)
mockery/mockery ~1.2
phpunit/phpunit ~9.0

conflicts
socialiteproviders/weixin *

```

**Comment by uptutu** [comment]
错误信息是平台方返回的 HTTP Response 里报错信息很明显 error_description":"The code passed is incorrect or expired." code 过期了。

我检查了一遍 Github 文档和代码逻辑，应该没有问题，请反复检查一下本地环境。欢迎补充提问。

@ginoking 

> PHP Fatal error: Uncaught Overtrue\Socialite\Exceptions\AuthorizeFailedException: Authorize Failed: {"error":"bad_verification_code","error_description":"The code passed is incorrect or expired.","error_uri":"https://docs.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#bad-verification-code"} in /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php:296
> Stack trace:
> #0 /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php(105): Overtrue\Socialite\Providers\Base->normalizeAccessTokenResponse()
> #1 /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php(67): Overtrue\Socialite\Providers\Base->tokenFromCode()
> #2 /var/www/alpha/login1.php(18): Overtrue\Socialite\Providers\Base->userFromCode()
> #3 {main}
> thrown in /var/www/alpha/vendor/overtrue/socialite/src/Providers/Base.php on line 296
> 
> github、facebook、linkedin皆遇到

**Comment by tripbnb66** [comment]
Please help to close this ticket.
Thank you.
