### ISSUE TITLE
Severity: error --> Exception: Undefined class constant 'VERSION' /app/vendor/overtrue/socialite/src/Providers/GoogleProvider.php 68

### ISSUE THREAD

**Issue by devlamine** [overtrue/socialite#205]
php version is v7.3
After Update to ~2.x the problem was appear :Severity: error --> Exception: Undefined class constant 'VERSION' /app/vendor/overtrue/socialite/src/Providers/GoogleProvider.php 68

**Comment by overtrue** [comment]
which version of `guzzlehttp/guzzle` have you installed?

**Comment by devlamine** [comment]
thank you for your response
"version": "7.2.0"

**Comment by overtrue** [comment]
@devlamine may by you should upgrade to 3.x to fixed it, or downgrade guzzle to 6.5.x.

**Comment by devlamine** [comment]
is version 3.x compatible with php7.3?

**Comment by overtrue** [comment]
@devlamine sorry, php 7.4+, You may want to consider upgrading your PHP, after all, there is basically no difference between 7.3 and 7.4.
