### ISSUE TITLE
微信PC扫码登陆，会显示蓝色的网址，然后跳转

### ISSUE THREAD

**Issue by ideaviewes** [overtrue/socialite#213]
php版本：7.4
overtrue/socialite版本：2.0.23
具体代码如下
` public function weichatLogin(){

        $config=config("socialite.");

        $manager = new \Overtrue\Socialite\SocialiteManager($config);

        return $manager->driver('wechat')->scopes(['snsapi_login'])->redirect();

   }`
截图如下
![1](https://user-images.githubusercontent.com/5431843/113368895-70171000-9392-11eb-9e6a-e58045602738.jpg)

有没有办法把这个蓝色的网址和请求头给隐藏掉，这样体验不太好

**Comment by overtrue** [comment]
```diff
- return $manager->driver('wechat')->scopes(['snsapi_login'])->redirect();
+ $manager->driver('wechat')->scopes(['snsapi_login'])->redirect()->send(); exit;
```

**Comment by ideaviewes** [comment]
@overtrue ,可以了，谢谢您！
