### ISSUE TITLE
飞书平台的 mapUserToObject 里的id v2是open_id,v3这里是user_id

### ISSUE THREAD

**Issue by FollowZero** [overtrue/socialite#214]
我做升级的时候，这个地方用open_id符合我的需求。我复制修改您的，自定义了一个

**Comment by uptutu** [comment]
如果 ->user 里没有想要的字段，可以从 raw 字段获取平台返回的原数据的所有字段。

$user->getRaw()

**Comment by FollowZero** [comment]
谢谢提醒，每个平台的用户唯一标识字段都不一样。我是想通过一个统一的方式获取到这值。
