### ISSUE TITLE
php版本为什么要7.4有点高吖。。。

### ISSUE THREAD

**Issue by wzxaini9** [overtrue/socialite#215]
我觉得现在7.2用的更多吧

**Comment by overtrue** [comment]
新版本要求 7.4，如果你的版本满足不了可以选择使用 2.xn 哈，PHP 7.4 官方还有几个月就停止维护了，明年（28 Nov 2022）连安全性问题都不再修复了。

> 7.2 去年下半年就停止了安全性维护，出个漏洞官方都不修了。建议还是升级吧。
