### ISSUE TITLE
GoogleProvider报错

### ISSUE THREAD

**Issue by xcorp1986** [overtrue/socialite#218]
src/Providers/GoogleProvider.php 68行
$postKey = (1 === version_compare(ClientInterface::VERSION, '6')) ? 'form_params' : 'body';
应为
$postKey = (1 === version_compare(ClientInterface::MAJOR_VERSION, '6')) ? 'form_params' : 'body';

**Comment by uptutu** [comment]
如果可以的话，建议您升级使用 social 3.x

**Comment by xcorp1986** [comment]
好的，改用3.x并做了适配，多谢
