### ISSUE TITLE
QQprovider里的getUserByToken方法第一个response存在错误

### ISSUE THREAD

**Issue by tradzero** [overtrue/socialite#22]
新版的QQprovider里134行 请求openid的时候新加入了一个unionid=1的参数，就是因为这个原因，后续的openid没法获取到 导致没法获取到用户信息
![image](https://cloud.githubusercontent.com/assets/13845447/19302365/5f3b5a10-9096-11e6-9be1-a5761e751e4c.png)
上面是加了&unionid的结果
![image](https://cloud.githubusercontent.com/assets/13845447/19302378/6ef3c528-9096-11e6-808b-c1714b410e92.png)
这个是不加

劳烦大大看看是什么原因？ 还有新版加入这个是为了什么呢？

**Comment by overtrue** [comment]
@andares

**Comment by andares** [comment]
卧糟，QQ接口不会这么二吧……

**Comment by overtrue** [comment]
@andares 其实我想问那个 unionid 文档在哪，找了半天没发现

**Comment by andares** [comment]
@overtrue QQ的客服明确告诉我，没有文档（根本没来得及写），这个接口是**发邮件**申请打通应用间数据后，邮件回复告之我的。我还以为跟微信一样应用连接后自动返回unionid呢。

已经发pull request修正问题，现在要手动调```$sdk->withUnionId()->user()```才会添加unionid

**Comment by overtrue** [comment]
@andares 好吧，厉害，没来得及写，哈哈 😆

**Comment by overtrue** [comment]
@tradzero 已经 fix，请更新版本 1.0.18

**Comment by tradzero** [comment]
@overtrue @andares  好的 谢谢大大们
