### ISSUE TITLE
希望支持企业微信的扫码授权登录

### ISSUE THREAD

**Issue by devpwb** [overtrue/socialite#241]
感谢大神的这个扩展包，目前好像只有企业微信的网页授权登录，那是手机端用的，桌面端的“扫码授权登录”没有，希望能加上；
相关文档：https://developer.work.weixin.qq.com/document/path/91019

**Comment by overtrue** [comment]
扫码登录不是 OAuth 啊，搞进来不伦不类的

PWB ***@***.***>于2022年7月7日 周四16:16写道：

**Comment by devpwb** [comment]
![CleanShot 2022-07-07 at 17 15 30](https://user-images.githubusercontent.com/108863587/177738357-fbb0c388-5422-4a31-9b66-c520dd7c880d.png)
补充图片

**Comment by overtrue** [comment]
好吧，我来优化一下，应该是以前被他们傻逼的文档搞蒙蔽了……

**Comment by overtrue** [comment]
@devpwb 加我Q 44294631
