### ISSUE TITLE
能否为AbstractProvider提供一个getRequest方法

### ISSUE THREAD

**Issue by deathkel** [overtrue/socialite#38]
我在使用您的EASYWECHAT项目，您在oauth中使用了原生的session驱动，我需要将它改为redis驱动，但是由于easywechat容器中的oauth对象是一个wechatProvider而不是socialite，使得我没法更改session驱动

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L282-L285

**Comment by deathkel** [comment]
cool ! man
