### ISSUE TITLE
微信获取 userinfo 请求中的 lang 是否可以修改

### ISSUE THREAD

**Issue by satgi** [overtrue/socialite#39]
[https://github.com/overtrue/socialite/blob/master/src/Providers/WeChatProvider.php#L121](https://github.com/overtrue/socialite/blob/master/src/Providers/WeChatProvider.php#L121)

微信获取 userinfo 请求中的 lang 是否可以修改或者去掉？现在应该是写死的吧。

**Comment by overtrue** [comment]
@satgi 为啥要去掉或者修改呢？有没有可参考的地方？

**Comment by satgi** [comment]
@overtrue 感谢回复

我们的需求是从微信获取用户的 country/region 信息，跟我们自己的 country/region 数据库匹配，最精确的方式是通过 country code

[文档](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317853&token=&lang=zh_CN) 中说 `lang` 可以设置返回的国家地区语言版本，经测试不传 lang 的时候会返回 country code，以下是测试结果：

#### lang=zh_CN
```
{
  "nickname": "xx", 
  "country": "中国",
  ...
}
```

#### lang=zh_TW
```
{
  "nickname": "xx", 
  "country": "中國",
  ...
}
```

#### lang=en
```
{
  "nickname": "xx", 
  "country": "China",
  ...
}
```

#### 不传 lang
```
{
  "nickname": "xx", 
  "country": "CN",
  ...
}
```

**Comment by overtrue** [comment]
@satgi 那我去掉吧

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite/releases/tag/1.0.21

**Comment by overtrue** [comment]
@satgi 上次你这个需求的修改让一部分同学使用出现了问题，我已经还原修改，但是增加了可选方案：

你在使用的时候可以 `$socialite->driver('wechat')->withCountryCode()->user();` 来达到返回 country code 的目的，详情请参考：
> https://github.com/overtrue/socialite/commit/e749ea09ab7b356a94c823804e95650efc616337

**Comment by satgi** [comment]
@overtrue 好的，感谢
