### ISSUE TITLE
如何自定义登录时的scope？

### ISSUE THREAD

**Issue by bestony** [overtrue/socialite#42]
因为应用场景不同，可能希望拿到一些别的数据，比如repo信息。我查了下api  文档，似乎和跳转时的 scope有关

**Comment by overtrue** [comment]
@bestony 所以你 README 都没看完？https://github.com/overtrue/socialite#scope

**Comment by bestony** [comment]
抱歉，打扰了。跟着别人的教程操作的。没有注意到这里。

**Comment by overtrue** [comment]
@bestony 没事
