### ISSUE TITLE
InvalidStateException at refresh with Google driver

### ISSUE THREAD

**Issue by JeroenSteen** [overtrue/socialite#43]
When I refresh the page I get: `Uncaught exception 'Overtrue\Socialite\InvalidStateException'`. Is it possible to fix that behaviour? I also saw `stateless = false` at Laravel/Socialite.

The exception is being thrown when I call: `$google->user();`.

**Comment by overtrue** [comment]
@JeroenSteen Which driver did you choose?

**Comment by overtrue** [comment]
@JeroenSteen Which framework?

**Comment by overtrue** [comment]
@JeroenSteen `When I refresh the page` ? which page? after authorized page?

**Comment by overtrue** [comment]
The right logic is following:

> click btn(Google Login) -> redirect to google -> click OK -> redirect back to your site callback route -> got user info -> **REDIRECT TO YOUR BUSINESS PAGE**

**Comment by JeroenSteen** [comment]
I'm using only PHP, I tried refreshing my index.php and admin.php page.
I want to secure my admin page, with Google as Auth.

This is my code:

```
//Config.php
$domain = "..";

$config = [
    'google' => [
        'client_id'     => '...apps.googleusercontent.com',
        'client_secret' => ..',
        'redirect'      => $domain.'/admin.php',
    ],
];

$scopes = [
		'profile',
		'https://www.googleapis.com/auth/contacts.readonly'
	];

//Index.php
require_once("vendor/autoload.php");
require_once("config.php");

use Overtrue\Socialite\SocialiteManager;

$socialite = new SocialiteManager($config);
$response = $socialite->driver('google')->scopes($scopes)->redirect();

$response->send();

//Admin.php
require_once("vendor/autoload.php");
require_once("config.php");

use Overtrue\Socialite\SocialiteManager;

$socialite = new SocialiteManager($config);
$google = $socialite->driver('google')->scopes($scopes);
//Sometimes throws the exception
$user = $google->user();
```

So I want to the redirect back the user to index.php, if $user is not valid.

**Comment by overtrue** [comment]
@JeroenSteen Yes, I got it. you just need a page to avoid refresh:

index.php:  redirect to google
callback.php: receive the user info and put it into session and redirect to admin.php
admin.php: fetch user from session.

😄 

> The error reason is: The url of you admin.php include the callback query(code&state), but the state has been validated and destroyed(deleted from session store) by `$google->user()` logic. So, when you refresh the page, call `$google->user()` again, the state is old value, and there is no state in session, erred.

**Comment by JeroenSteen** [comment]
I understand the flow, save it with $_SESSION to use it in admin.php. That will be suitable for things like username and avatar :)

**Comment by overtrue** [comment]
@JeroenSteen Yes!
