### ISSUE TITLE
With request for Google contacts feed

### ISSUE THREAD

**Issue by JeroenSteen** [overtrue/socialite#44]
I checked "Additional parameters" in the README and I have one question. How to add request for getting Google contacts? Can it be in the callback.php, like so:

```
$google = $socialite
	->driver('google')
	->scopes($scopes)
	->with(['contacts', 'https://www.google.com/m8/feeds/contacts/default/full?alt=json&max-results=400']);
$google->contacts;
```

Feed/scope based on tutorial: [Mydnic](https://mydnic.be/post/how-to-get-all-gmail-contacts-with-laravel-5).

**Comment by overtrue** [comment]
sorry, this library cannot do that, just for user login.
