### ISSUE TITLE
FacebookProvider: AuthorizeFailedException thrown due to response parse error.

### ISSUE THREAD

**Issue by Muffinman** [overtrue/socialite#57]
Hi,

I'm trying to use this package with Facebook oauth, but the access token response is not being parsed correctly:

> ( ! ) Fatal error: Uncaught exception 'Overtrue\Socialite\AuthorizeFailedException' with message 'Authorize Failed: {"{\"access_token\":\"REMOVED\",\"token_type\":\"bearer\",\"expires_in\":5182660}":""}' in PROJECT/vendor/overtrue/socialite/src/Providers/AbstractProvider.php on line 400
( ! ) Overtrue\Socialite\AuthorizeFailedException: Authorize Failed: {"{\"access_token\":\"REMOVED\",\"token_type\":\"bearer\",\"expires_in\":5182660}":""} in PROJECT/vendor/overtrue/socialite/src/Providers/AbstractProvider.php on line 400

> Call Stack
\#	Time	Memory	Function	Location
1	0.0001	242856	{main}( )	.../index.php:0
2	0.0025	506752	require_once( 'PROJECT/scripts/account.php' )	.../index.php:38
3	0.0025	507040	ACCOUNT->login_social_callback( )	.../account.php:42
4	0.0044	728120	Overtrue\Socialite\Providers\AbstractProvider->user( )	.../account.php:699
5	0.0045	729472	Overtrue\Socialite\Providers\FacebookProvider->getAccessToken( )	.../AbstractProvider.php:173
6	0.4131	969080	Overtrue\Socialite\Providers\FacebookProvider->parseAccessToken( )	.../FacebookProvider.php:89
7	0.4131	969832	Overtrue\Socialite\Providers\AbstractProvider->parseAccessToken( )

The problem code in FacebookProvider.php:

````
    /**
     * Get the access token for the given code.
     *
     * @param string $code
     *
     * @return \Overtrue\Socialite\AccessToken
     */
    public function getAccessToken($code)
    {
        $response = $this->getHttpClient()->get($this->getTokenUrl(), [
            'query' => $this->getTokenFields($code),
        ]);

        return $this->parseAccessToken($response->getBody());
    }

    /**
     * {@inheritdoc}
     */
    protected function parseAccessToken($body)
    {
        parse_str($body, $token);

        return parent::parseAccessToken($token);
    }
````

This causes the whole response body to be incorrectly parsed into a array with the key being the json text, and the value being null.

To correct the issue I just removed the methods from FacebookProvider.php and let it use the AbstractProvider methods, which seems to work fine.

Perhaps this is a change in the response that Facebook are now sending? I'm using OG v2.9 in my app.

EDIT: My full versions:

````
➤ composer info
abraham/twitteroauth      0.7.2  The most popular PHP library for use with the Twitter OAuth REST API.
codegun/phpmailer-lite    1.0.0  PHPMailerLite By PHPMailer
guzzlehttp/guzzle         6.2.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1 Guzzle promises library
guzzlehttp/psr7           1.4.2  PSR-7 message implementation that also provides common utility methods
overtrue/socialite        1.0.25 A collection of OAuth 2 packages that extracts from laravel/socialite.
phpoffice/phpexcel        1.8.1  PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
psr/http-message          1.0.1  Common interface for HTTP messages
symfony/http-foundation   v3.2.8 Symfony HttpFoundation Component
symfony/polyfill-mbstring v1.3.0 Symfony polyfill for the Mbstring extension
````

````
➤ php -v
PHP 7.1.5 (cli) (built: May 13 2017 13:28:23) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
````

**Comment by overtrue** [comment]
https://developers.facebook.com/docs/apps/changelog

> from v2.2 -> 2.3 response changed from urlencode content to JSON format.

**Comment by overtrue** [comment]
I have make a new release with the following changes. https://github.com/overtrue/socialite/releases/tag/1.0.26
https://github.com/overtrue/socialite/commit/7f4ad481a5ca8860aeb2c116836d60618e50853f

**Comment by Muffinman** [comment]
Thanks for the quick fix!

**Comment by overtrue** [comment]
you are welcome.
