### ISSUE TITLE
关于微博用户拒绝授权

### ISSUE THREAD

**Issue by mugenaki** [overtrue/socialite#58]
通过socialite跳转至微博授权页，页面提示用户登录微博，此时用户点击【取消】，微博会跳转至程序的callback页

继而GuzzleHttp抛出ClientException异常：
```
Client error: `POST https://api.weibo.com/2/oauth2/access_token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_code":21325,"request":"/2/oauth2/access_token","error_uri":"/2/oauth2/access_token","err
```
跳转callback：
`
foo.com/weibo/callback?error_uri=%2Foauth2%2Fauthorize&error=access_denied&error_description=user%20denied%20your%20request.&error_code=21330&state=8708586829ca1134ced0f754b00c2cd15c03157e
`

两处的error_code分别为
invalid_grant	21325	提供的Access Grant是无效的、过期的或已撤销的
access_denied	21330	用户或授权服务器拒绝授予数据访问权限

Thx.

**Comment by overtrue** [comment]
所以你的意思是？

**Comment by mugenaki** [comment]
抱歉描述不清,正准备改来着，没想到你秒回。

一般在callback都是直接执行获取用户信息操作
```
$user = $socialite->driver('weibo')->user();
```
但是微博用户拒绝授权也会跳转到callback，此时这个操作拿不到用户信息....

我想是否可以提供一个专门的无法获取用户信息的异常类，而不是GuzzleHttp的ClientException异常呢？

再次感谢。

**Comment by overtrue** [comment]
我建议 try catch 比较好

**Comment by mugenaki** [comment]
是的，我使用了try catch，并捕获了AuthorizeFailedException 异常

但是在这种情况下抛出的却是GuzzleHttp的ClientException异常，会令人很迷惑。

是否可以将我上面所说的用户操作导致的ClientException异常也整合进AuthorizeFailedException或者另一个有这个包提供的异常呢？

**Comment by overtrue** [comment]
我来改进吧，我关掉 client 异常

**Comment by overtrue** [comment]
http://docs.guzzlephp.org/en/stable/request-options.html#http-errors

**Comment by mugenaki** [comment]
嗯~谢谢.
👍
