### ISSUE TITLE
功能写得非常好用,希望能增加一个钉钉的 

### ISSUE THREAD

**Issue by locxiang** [overtrue/socialite#61]
功能写得非常好用,如果超神有空增加一个钉钉的就更好了

**Comment by uptutu** [comment]
钉钉的鉴权规则不太一样，没有遵循 OAuth2 所以嵌入这个拓展包可能有点不太合适。

V3.0 版本在路上了，已经支持了钉钉的第三方个人应用扫码登陆。只能获取到用户的 nickname 还有用户在钉钉上的 openid 和 unionid 
仅仅实现整合了“扫码登录第三方网站”： https://ding-doc.dingtalk.com/doc#/serverapi3/mrugr3

如果有关于 DingTalk 的更多功能的开发，比如对授权企业进行更多的操作。
建议使用官方 SDK (https://ding-doc.dingtalk.com/doc#/faquestions/vzbp02)
推荐一个不错的第三方 SDK ：EasyDingTalk (https://github.com/mingyoung/dingtalk)

**Comment by ShuiPingYang** [comment]
请问3.0版本什么时候上线呢？非常期待呢

**Comment by overtrue** [comment]
@ShuiPingYang 待充分测试后就发版，要是有空也欢迎 dev-develop 装起来帮忙测试哈哈哈

**Comment by ShuiPingYang** [comment]
@overtrue 好的呢，请问这个包如何在项目中拓展其他未实现的登陆方式呢？例如苹果支付，推特登录，希望有个文档能介绍一下。

**Comment by overtrue** [comment]
苹果支付 不是 OAuth 登陆相关的吧？推特不是 OAuth 2.0 所以重合度很低，可以找其他 SDK 实现

**Comment by ShuiPingYang** [comment]
@overtrue 我只是想和使用微信provider类似，例如下面这样使用twitter，该怎么处理？实现方式我自己实现，只是想让调用方式统一
```php
$socialite->driver('twitter')->user();
```

**Comment by overtrue** [comment]
我说过了啊，它不是 OAuth 2，直接用 laravel/socialite 或者参考它的实现自己做咯

**Comment by overtrue** [comment]
https://github.com/overtrue/socialite#dingtalk
