### ISSUE TITLE
能增加对Twitter OAuth的支持吗？

### ISSUE THREAD

**Issue by iVanilla** [overtrue/socialite#62]
支持Facebook，居然不支持Twitter？这对国外网站是刚需。

**Comment by overtrue** [comment]
Twitter 是 OAuth 1， 集成起来太费劲就不想弄了，你要用 twitter 请使用 laravel/socialite

**Comment by iVanilla** [comment]
@overtrue 既然如此，那我有空时参考laravel/socialite代码做一下，然后提个PR。
