### ISSUE TITLE
微信的access-token应该是要每次获取的，那配置文件里怎么写？

### ISSUE THREAD

**Issue by jourdon** [overtrue/socialite#73]
微信提供的只有client_id，client_secret，这个access-token要怎么写？

**Comment by overtrue** [comment]
没有要求你填写 access_token 啊

**Comment by jourdon** [comment]
'wechat_open' => [
    'client_id'     => 'your-app-id',
    'client_secret' => ['your-component-appid', 'your-component-access-token'],
    'redirect'      => 'http://localhost/socialite/callback.php',
]
你的文档里client_secret里后面写的是access-token，是写错了？应该是client_secret？

**Comment by overtrue** [comment]
开放平台你就得自己实现获取  access_token 的方法，然后将值传进来

**Comment by overtrue** [comment]
开放平台的 access-token 不是微信推送给你的么？

**Comment by jourdon** [comment]
获取到access-token 然后再写回到config/services.php里? 这样有点奇怪唉

**Comment by overtrue** [comment]
没办法，那部分逻辑不应该包含在这个包里，每家都有不同的存储方案，放到这里就不对了

**Comment by overtrue** [comment]
对于这个包来讲，没有 `config/services.php` 一说，只有 new 的时候传配置，至于这个配置是从文件还是从其它地方来，此包并不关心，只要你实例化 Manager 的时候是数组就 OK 了 。

**Comment by jourdon** [comment]
ok.了解了。所以再方法之前获取到access-token再放到数组里就OK了。谢谢超哥解答！

**Comment by mingyoung** [comment]
@jourdon 可以看看这里的实现：https://github.com/overtrue/wechat/blob/develop/src/OpenPlatform/Application.php#L71

**Comment by jourdon** [comment]
@mingyoung 好的谢谢
