### ISSUE TITLE
AbstractProvider::getHttpClient() 每次调用都获取新的 Client 实例

### ISSUE THREAD

**Issue by edwardaa** [overtrue/socialite#76]
[相关代码](https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L462)如下：

```php
/**
 * Get a fresh instance of the Guzzle HTTP client.
 *
 * @return \GuzzleHttp\Client
 */
protected function getHttpClient()
{
    return new Client(self::$guzzleOptions);
}
```

公司项目希望注入一个全局的并且自定义的 Client，但注释 （Get a fresh instance of the Guzzle HTTP client) 中提到获取一个 **fresh** 实例，即每次调用都获取一个新的实例，这样做有什么特别的用意吗？

**Comment by overtrue** [comment]
因为在实际场景中，授权通常只用一次请求嘛

**Comment by edwardaa** [comment]
OK, 理解啦
