### ISSUE TITLE
能不能增加个手机短信注册登录的接口

### ISSUE THREAD

**Issue by jnuc093** [overtrue/socialite#8]
能不能增加个手机短信注册登录的接口，类似于Boss app直聘的登录方式。

**Comment by overtrue** [comment]
@jnuc093 短信服务商N家，无法适配。。。

**Comment by jnuc093** [comment]
可以和一些厂商合作。调用他们的API。顺便收个他们的费合作搞个推广什么的。

**Comment by jnuc093** [comment]
什么 云短信、51短信 ...

**Comment by overtrue** [comment]
@jnuc093 你可以自行拓展，我不觉得在这个包里应该放这些并不是大家都用的。
