### ISSUE TITLE
symfony 的错误，不知道在这里说是不是合适

### ISSUE THREAD

**Issue by greedying** [overtrue/socialite#87]
是这样，`symfony/http-foundation/Session/Storage/NativeSessionStorage.php` 的 106 行如下：

```php 
session_cache_limiter('')
```

这句对session做了一些操作。

我的逻辑，是判断用户是不是登陆，没登录就调用 ` easyWechat->getAuthUrl` ，然后跳转到授权链接。

之前代码是没问题的， 能跑。

不过我刚升级了php 7.2.2，就跳出了一个错误

``php
session_cache_limiter(): Cannot change cache limiter when session is active
``

我研究了下，大概新版本的php中， session_cache_limiter 必须放在session_start前面。然而我又需要session 去判断是否登陆。

死循环了，求新有有风险。

不知道有没有人遇到这个情况，有解决方案说一下，谢谢。否则我只能回退到老版本了。。

**Comment by overtrue** [comment]
似乎你需要更新一下代码：https://github.com/symfony/http-foundation/commit/d22fa517fee4cf42fcfbf942cdfa3a1791e002a2#diff-73c4b14ed38655a2b0c09b1e14a2b8f4

**Comment by greedying** [comment]
是的。我也发现了，汗。  我直接到项目里看最新代码是否还有那行，发现去掉了。然后尝试composer update 了一下，发现可用了。 打扰。
