### ISSUE TITLE
有没有哪个方法直接通过access_token获取用户信息？

### ISSUE THREAD

**Issue by iScript** [overtrue/socialite#9]
因为是在app上做第三方登录，比如用友盟的qq登录，登录成功后已经获取到了uid和access_token，我想把uid和access_token传回到服务器进行验证和获取信息。
有没有哪个方法直接通过access_token获取用户信息？

**Comment by overtrue** [comment]
`composer require "overtrue/socialite:dev-develop"`  先试一下，用法 ：


```php
use Overtrue\Socialite\AccessToken;
$accessToken = new AccessToken(['access_token' => xxxx]);
$user = $socialite->user($accessToken);
```

**Comment by iScript** [comment]
```
$socialite = new \Overtrue\Socialite\SocialiteManager($config);
 $a_token= new \Overtrue\Socialite\AccessToken(['access_token' => "dddd"]);
 $user = $socialite->driver('qq')->user($a_token);
```
这样对吗？ 报了这个错  没有openid

Whoops, looks like something went wrong.

1/1
ErrorException in QQProvider.php line 129:
Undefined index: openid
in QQProvider.php line 129
at HandleExceptions->handleError('8', 'Undefined index: openid', '/private/var/app/www/WT-Web/vendor/overtrue/socialite/src/Providers/QQProvider.php', '129', array('token' => object(AccessToken), 'response' => object(Response))) in QQProvider.php line 129

**Comment by overtrue** [comment]
@iScript 你的 token 过期了吧？

**Comment by iScript** [comment]
恩，我在试试
