### ISSUE TITLE
放到服务器之后github登录回调的时候报错,但是本地正常,开发环境php7.2+laravel5.5+ngix,请问大神怎么处理？

### ISSUE THREAD

**Issue by hcweb** [overtrue/socialite#92]
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see //curl.haxx.se/libcurl/c/libcurl-errors.html

**Comment by overtrue** [comment]
https://www.google.com.hk/search?q=unable+to+get+local+issuer+certificate&oq=unable+to+get+local+issuer+certificate&aqs=chrome..69i57.280j0j7&sourceid=chrome&ie=UTF-8
