### ISSUE TITLE
Uncaught Overtrue\Socialite\InvalidStateException

### ISSUE THREAD

**Issue by Div-Man** [overtrue/socialite#94]
write `$user = $socialite->driver('github')->user();` 

and displays an error

`Fatal error: Uncaught Overtrue\Socialite\InvalidStateException in C:\OSPanel\domains\oauth\vendor\overtrue\socialite\src\Providers\AbstractProvider.php:189 Stack trace: #0 C:\OSPanel\domains\oauth\index.php(21): Overtrue\Socialite\Providers\AbstractProvider->user() #1 {main} thrown in C:\OSPanel\domains\oauth\vendor\overtrue\socialite\src\Providers\AbstractProvider.php on line 189`

**Comment by overtrue** [comment]
check you session storage. 

> https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L404-L413

**Comment by Div-Man** [comment]
how to create an instance AbstractProvider?

**Comment by overtrue** [comment]
You don't need to create a provider instance, because the `$socialite->driver('github')` did it. You just need to check the state value in session, which not equals to state value in URL query. 

https://github.com/overtrue/socialite/blob/master/src/Providers/AbstractProvider.php#L412

**Comment by Div-Man** [comment]
Fatal error: Uncaught Error: Call to protected method Overtrue\Socialite\Providers\AbstractProvider::hasInvalidState() from context '' in C:\OSPanel\domains\oauth\index.php:17 Stack trace: #0 {main} thrown in C:\OSPanel\domains\oauth\index.php on line 17

```
<?php
require 'vendor/autoload.php';

use Overtrue\Socialite\SocialiteManager;


$config = [
    'github' => [
        'client_id'     => 'e99c1f3911738a02f4f4',
        'client_secret' => '6b3a28b87cd13a367cbd405f630bfb5da01ad63c',
        'redirect'      => 'http://oauth',
    ],
];

$socialite = new SocialiteManager($config);

$response = $socialite->driver('github')->hasInvalidState();
```

**Comment by overtrue** [comment]
Plz don't call it, because it is a protected method, you can add debug code to the related lines.

**Comment by hunteryun** [comment]
same issue, I con't get the user info in callback.php

**Comment by Div-Man** [comment]
The problem is not solved
