### ISSUE TITLE
php 5点几的版本如何使用socialite？

### ISSUE THREAD

**Issue by kl521516** [overtrue/socialite#95]
php 5点几的版本如何使用socialite？

**Comment by overtrue** [comment]
抱歉不支持 PHP 5, 仅支持 PHP 7.0 或以上版本

**Comment by kl521516** [comment]
我们网站程序升级到php7就报500错误，所以没法使用socialite，你能教我修改socialite部分代码来支持php5点几的版本吗？

**Comment by overtrue** [comment]
PHP 7 都发布快3年了，我还是比较建议你去升级 PHP 的版本，因为现在很多框架与程序都要求 PHP 7 了，报 500 错误按日志修改一下就好了，而且一般都是非常小的修改，我对很多过项目进行过升级处理，均不超过5小时搞定。如果你硬是要修改 socialite 源码的话，你看看 PHP 7 的特性，比如返回值类型，参数类型约束这些地方修改基本就可以了。

**Comment by kl521516** [comment]
php5点几的版本用error_reporting(E_ALL);就可以输出错误信息，但php7我用下面一堆代码也不输出错误信息，能教我怎么设置或者添加什么代码就能输入错误信息吗？

set_error_handler("_errorHandler");
set_exception_handler("_exceptionHandler");
register_shutdown_function("check_for_fatal");
error_reporting(E_USER_ERROR);
error_reporting(E_ALL);
ini_set('display_errors', "on");
ini_set('log_errors', "on");

var_dump(error_reporting());

**Comment by overtrue** [comment]
没用框架？

把这些都注释掉：

```
set_error_handler("_errorHandler");
set_exception_handler("_exceptionHandler");
register_shutdown_function("check_for_fatal");
```
在 php.ini 里修改以下两项：

```
ini_set('display_errors', "on");
ini_set('log_errors', "on");
```

**Comment by overtrue** [comment]
然后重启 php-fpm

**Comment by kl521516** [comment]
感谢你的答复，但我按你方式修改了php.ini，重启了php-fpm， 也重启了nginx，注释了那三行代码，但网页端还报500错误，php-fpm和nginx日志文件都没有任何错误信息输出

**Comment by overtrue** [comment]
检查你的 php 日志配置到哪里的，不应该没有报错日志

**Comment by overtrue** [comment]
nginx 要打开  error_log

**Comment by kl521516** [comment]
error_log  /home/wwwlogs/nginx_error.log  crit;
nginx配置文件显示开启了错误日志，但那个日志文件里没有任何信息输出

**Comment by overtrue** [comment]
https://my.oschina.net/u/205403/blog/142631

**Comment by overtrue** [comment]
并不是所有选项都可以用 `ini_set` 来修改的：

![image](https://user-images.githubusercontent.com/1472352/40092041-beb72ae8-58ed-11e8-9d98-77466d8a6084.png)

> http://php.net/manual/zh/function.ini-set.php
> http://php.net/manual/zh/ini.list.php

**Comment by kl521516** [comment]
http://58.87.121.180/site/php.ini.txt
http://58.87.121.180/site/nginx.conf.txt

上面两个链接分别是我现在php和nginx的配置文件


error_reporting(E_USER_ERROR);
error_reporting(E_ALL);
ini_set('display_errors', "on");
ini_set('log_errors', "on");

var_dump(error_reporting());


set_error_handler(function ($errno,$errstr,$errfile,$errline)//常用的四个参数  
{
    echo "错误等级：".$errno."<br>错误信息：".$errstr."<br>错误的文件名：".$errfile."<br>错误的行号：". $errline;
    exit();
});

这是我php的代码，麻烦你有时间时帮我看看

**Comment by overtrue** [comment]
你为啥一定要 set_error_handler 呢？让它直接抛出来原生显示不就得了吗？

1. 把你 nginx.conf 上的 `error_log` 那行删除
2. 在 vhost/*.conf 对应的网站配置里添加:
```
error_log /var/log/nginx/error.log; // 确保文件路径可写，实在不行你就写成 /tmp/nginx.site-name.error.log
```
3. php.ini 中：

```
display_errors = Off 修改为 On
```

4. 把你的 php 代码里对 ini_set 相关的都去掉，set_error_handler 也删除，如果你要继续这么写，抱歉我没这么多时间帮你。

5. 重启 php 与 nginx 

6.  在服务器命令行执行，并粘贴结果：

```
$ php -i | grep error_
```

**Comment by kl521516** [comment]
1、再次感谢你的答复，错误信息现在已经可以输出了，是因为php.ini里面有两个display_errors，第一个是on，第二个是off，我当时在命令行里只会查找，不会查下一个，只改了第一个才造成错误信息一直无法输出。

2、在php7的环境下程序报了一堆错误，改了一个又来一个，很多都是框架里的里面的东西，像连接数据库都报错，我想了想，还是用php5点的几的版本算了，你能不能教我怎么修改socialite里的代码才能在php5下运行

**Comment by overtrue** [comment]
我在最前面已经说过怎么改了，但是我可没有时间一行行给你列出来，作为一名开发者，你有必要弄清楚PHP 7和 5 的区别来。

xiaolin <notifications@github.com>于2018年5月16日 周三下午5:53写道：
