### ISSUE TITLE
如何只输出登录链接，不要直接跳转到授权登录页面

### ISSUE THREAD

**Issue by kl521516** [overtrue/socialite#96]
`$socialite = new SocialiteManager($facebook_config);
$response = $socialite->driver('facebook')->redirect();

echo $response;// or $response->send();`

如何只输出登录链接，不要直接跳转到授权登录页面，我们登录页面同时有好几种登录方式让用户选择

**Comment by overtrue** [comment]
`$response->getTargetUrl();`

**Comment by kl521516** [comment]
`$socialite_google = new SocialiteManager($config_google);
$response_google = $socialite_google->driver('google')->redirect();
echo $response_google->getTargetUrl();

echo("<hr>");

$socialite_facebook = new SocialiteManager($config_facebook);
$response_facebook = $socialite_facebook->driver('facebook')->redirect();
echo $response_facebook->getTargetUrl();`

你好，现在可以输出链接了，但同时输出google和facebook的授权登录链接就报如下错误，如果只输出一个就可以，请问这个问题该怎么解决

Fatal error: Uncaught exception 'Overtrue\Socialite\InvalidStateException' in /home/wwwroot/www/vendor/overtrue/socialite/src/Providers/AbstractProvider.php:182 Stack trace: #0 /home/wwwroot/www/google_login/socialite_callback.php(19): Overtrue\Socialite\Providers\AbstractProvider->user() #1 {main} thrown in /home/wwwroot/www/vendor/overtrue/socialite/src/Providers/AbstractProvider.php on line 182

**Comment by overtrue** [comment]
通常我们的做法是在前端模块给一个路由，比如：/login/weibo, /login/facebook, /login/google

当用户点这个链接的时候，你再去引导跳转：

```php
function redirectTo($provider) {
    return $socialite->driver($provider)->redirect();
}
```

**Comment by kl521516** [comment]
![wx20180521-113928](https://user-images.githubusercontent.com/1737460/40289573-c7417a22-5ceb-11e8-9ee4-05f01e875ac0.png)
![wx20180521-114016](https://user-images.githubusercontent.com/1737460/40289574-c7792f58-5ceb-11e8-96f3-f000020f8982.png)

你好，我们谷歌JavscriptSdk时，点登录授权时只会弹出一次，为什么用socialiteSDK时会弹出两次授权？

**Comment by kl521516** [comment]
用JavscriptSdk时，在选择账号界面点击用户名就会跳转到callback的链接上去，不会再显示“想要访问您的google账号”

**Comment by overtrue** [comment]
@kl521516 sorry, 这个就不清楚了，也许授权参数不一样吧。不是太清楚具体差别，没用过 javascript SDK

**Comment by kl521516** [comment]
好的，我自己再研究研究，谢谢你的耐心答复和帮助。
